name: deploy

on:
  push:
    branches:
      - ci-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -p 34873 -o "StrictHostKeyChecking no" root@5.161.42.171 << 'ENDSSH'
          cd /root/oam/oam-api
          git pull
          cp index.js /tmp/test
          journalctl -n10 > /tmp/log
          ENDSSH
